### ISSUE TITLE
Exposed Apache htpasswd file

### ISSUE THREAD

**Issue by RiRa12621** [litespeedtech/lsws-dockerfiles#2]
Potential security breach. See /template/htpasswd

**Comment by Code-Egg** [comment]
Hi,

Right. basically it's hashed, and we strongly recommend user to set their personal password right away. 
https://github.com/litespeedtech/lsws-docker-env#setting-the-webadmin-password

Best,
Eric

**Comment by RiRa12621** [comment]
It's fine that you recommend to have folks change it, hashing is not a very valid argument imho, espcecially md5crypt


```
$ cat passwd
admin:$1$RaqgGtmd$81EhmoqpWhiJJtCDRp0FX/
$ john passwd --show
admin:123456

1 password hash cracked, 0 left
```

**Comment by lars-hagen** [comment]
> It's fine that you recommend to have folks change it, hashing is not a very valid argument imho, espcecially md5crypt
> 
> ```
> $ cat passwd
> admin:$1$RaqgGtmd$81EhmoqpWhiJJtCDRp0FX/
> $ john passwd --show
> admin:123456
> 
> 1 password hash cracked, 0 left
> ```

Hi Rick,

Thank you for your message.

This was a design choice, due to the nature of docker. 

Litespeed auto generates a random password by default. We disabled that, because the docker image isn't built on the user end but on the CI(travis) end. So lets say we print the password to the console, it will be on travis, anyone can still see it. Lets say we generate the password when you start up the containers on your end, what if you ran `docker-compose up -d` then you dont see the logs. Now you have to try and look through the logs to find it. Lets say we store the randomly generated password in the environment, well its still in plain text. Sure we can encrypt it using a random hash but ultimately everything is still there. 

The goal with this setup was to have something simple that just works. Another problem with docker-compose up is that it doesn't allow for user interaction, if they did it would have solved this problem. We didn't want to over complicate things with this setup, we wanted to keep it as simple as possible, which was why we stuck with the default litespeed password.

You could argue that the password should be random, so when you run the setup first time, you would be forced to change it. But then we have to communicate that somehow to the user, would that be via stdout or a web page. And it has to be bullet proof so we don't introduce new problems.

I hope that cleared some things. If not feel free to write again, and if you a solution to the problem feel free to make a PR.

Best Regards
Lars
